# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# %% [markdown]
# # Plot Evolution of Storm Tracks and Atmospheric Fields
#
# This notebook demonstrates how to visualise tropical cyclone (TC) tracks
# overlaid on atmospheric field data. Use this to validate tracking algorithm
# outputs or create publication-ready animations.
#
# ### Workflow Overview
# 1. Configure paths and plotting parameters
# 2. Load and subset field data from NetCDF
# 3. Load and align track data from CSV files
# 4. Generate animated visualisation
# 5. (Optional) Save animation to file
#
# ### Data Prerequisites
# - NetCDF file containing atmospheric field data
# - Track CSV files generated by the TC tracking algorithm
#
# Both files can be produced by configuring a tc_hunt run with
# `store_type: "netcdf"` and cyclone tracking switched on, as e.g. done
# in `cfg/reproduce_helene.yaml`.
#
# ### Configuration
#
# **Path Settings**
# - `field_data` - path to NetCDF file (e.g.
#   `/path/to/outputs_reproduce_helene/helene_2024-09-24T00.00.00_mems0000-0013.nc`)
# - `track_dir` - folder containing track CSVs (e.g.
#   `/path/to/outputs_reproduce_helene/cyclone_tracks_te`)
#
# **Plotting Settings**
# - `variable` - field variable to plot (e.g., `'u10m'`, `'mslp'`).
#   Use `'wind_speed'` to compute 10m wind magnitude from `u10m` and `v10m`
# - `ensemble_member` - which ensemble member to visualise
# - `region` - geographic region (`'global'`, `'north_atlantic'`,
#   `'gulf_of_mexico'`)
#
# **Animation Settings**
# - `max_frames` - limit number of frames (set high to include full forecast)
# - `scale` - spatial coarsening factor (1 = full resolution, 2 = half, etc.)
# - `fps` - frames per second for animation playback

# %%
field_data = "/path/to/outputs_reproduce_helene/reproduce_helene_2024-09-24T00.00.00_mems0000-0013.nc"
track_dir = "/path/to/outputs_reproduce_helene/cyclone_tracks_te"

variable = "wind_speed"
ensemble_member = 3
region = "gulf_of_mexico"

max_frames = 99  # maximum number of frames to plot
scale = 1
fps = 4

# Map region label to (lat_min, lat_max, lon_min, lon_max).  Add new
# entries by appending another row.
REGIONS: dict[str, tuple[float, float, float, float]] = {
    "global": (-90, 90, 0, 359.75),
    "west_pacific": (9, 60, 100, 180),
    "north_atlantic": (9, 65, 250, 360),
    "gulf_of_mexico": (9, 45, 250, 310),
    "north_indian": (9, 40, 50, 100),
    "southern_pacific": (-40, 5, 140, 240),
}

try:
    lat_min, lat_max, lon_min, lon_max = REGIONS[region]
except KeyError as exc:
    raise ValueError(
        f"region {region!r} not yet implemented. "
        "Feel free to add it by providing lat/lon coords of the bounding "
        "box in the REGIONS dict."
    ) from exc

# %% [markdown]
# ### Step 1: Load Field Data
#
# - Read field data from NetCDF file
# - Sub-select region and variable; coarsen data if `scale > 1` for faster
#   iteration
# - Compute min/max values for consistent colour map across all timesteps

# %%
import os  # noqa: E402
import warnings  # noqa: E402

import cartopy.crs as ccrs  # noqa: E402
import cartopy.feature as cfeature  # noqa: E402
import matplotlib.animation as animation  # noqa: E402
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import xarray as xr  # noqa: E402
from cartopy.mpl.ticker import LatitudeFormatter, LongitudeFormatter  # noqa: E402
from loguru import logger  # noqa: E402

# fall back to ``print`` when not running inside an IPython kernel so that
# ``display(...)`` calls work both as a plain script and after
# ``jupytext --to notebook`` conversion
try:
    from IPython.display import display
except ImportError:

    def display(obj: object) -> None:  # type: ignore[misc]
        """Fallback display using print with xarray-friendly repr."""
        print(obj)


base_name = field_data.split("/")[-1].split(".")[0]
out_dir = f"outputs_{base_name}"

ds = xr.open_dataset(field_data)

# subselect lat/lon box, coarsen data if scale factor > 1
sub_ds = ds.sel(
    lat=list(np.arange(lat_min, lat_max, scale * 0.25)),
    lon=list(np.arange(lon_min, lon_max, scale * 0.25)),
)

# extract variable and obtain global min/max values
if variable == "wind_speed":
    sub_ds = np.sqrt(np.square(sub_ds.u10m) + np.square(sub_ds.v10m))
else:
    sub_ds = sub_ds[variable]

display(ds)

# %% [markdown]
# ### Step 2: Load Track Data
#
# This step loads and processes the cyclone track data to align with field
# timestamps.
#
# **Processing steps:**
# 1. **Select file** - filter by `ensemble_member` from filenames ignoring
#    the random seed
# 2. **Separate tracks** - split into individual DataFrames for each track
# 3. **Align timestamps** - reindex each track to match field data timesteps
#
# **Why reindexing matters:**
# Tracks may not have positions at every timestep (e.g., storm
# genesis/dissipation). Reindexing fills gaps with NaN, enabling
# frame-by-frame plotting without index errors.

# %%
from src.plt.data_handling import extract_tracks_from_file  # noqa: E402

track_dir = os.path.abspath(track_dir)

# extract time steps of field data
time_stamps = ds.time.values + ds.lead_time.values

# select track file of ensemble member
track_file = [
    f
    for f in os.listdir(track_dir)
    if f.endswith(".csv")
    and int(f.split("_mem_")[-1].split("_seed_")[0]) == ensemble_member
][0]
track_file = os.path.join(track_dir, track_file)

# extract tracks from prediction
tracks = extract_tracks_from_file(track_file)

# separate individual tracks in prediction
n_tracks = tracks["track_id"].iloc[-1] + 1
tracks = [tracks.loc[tracks["track_id"] == ii].copy() for ii in range(n_tracks)]

# align track data with simulation time steps
for ii in range(n_tracks):
    # extract the lines of tracks for which track['time'] is in time_stamps
    tracks[ii] = tracks[ii][tracks[ii]["time"].isin(time_stamps)]

    # fill the 'time' column with the time_stamps values
    tracks[ii] = tracks[ii].set_index("time").reindex(time_stamps).reset_index()

# %% [markdown]
# ### Step 3: Create Animation
#
# Creates an interactive animation where you can click through timesteps.
# Each frame shows the field data with tracks drawn progressively up to
# that point.

# %%
colour_map = "plasma"
projection = ccrs.PlateCarree()

# suppress line warnings stemming from potential NANs in track data
warnings.filterwarnings("ignore", message="invalid value encountered in linestrings")

# get index of ensemble member
ensemble_idx = np.argwhere(ds.ensemble.values == ensemble_member)[0, 0]

# get min and max vals for colour map (read using named dims for clarity)
member_field = sub_ds.isel(ensemble=ensemble_idx)
min_val = float(np.min(member_field))
max_val = float(np.max(member_field))


# define plots
def make_figure() -> tuple[plt.Figure, plt.Axes]:
    """Create a figure with a single PlateCarree subplot."""
    fig = plt.figure(figsize=(11, 7))
    ax = fig.add_subplot(1, 1, 1, projection=projection)

    lon_formatter = LongitudeFormatter(zero_direction_label=False)
    lat_formatter = LatitudeFormatter()
    ax.xaxis.set_major_formatter(lon_formatter)
    ax.yaxis.set_major_formatter(lat_formatter)

    return fig, ax


# make animation
plt.rcParams["animation.html"] = "jshtml"
fig, ax = make_figure()


def make_frame(frame: int) -> plt.Artist:
    """Render a single animation frame with field data and tracks."""
    logger.info(
        f"processing frame {frame+1} of {min(max_frames, sub_ds.sizes['lead_time'])}"
    )

    # Clear previous plot objects
    for artist in ax.get_children():
        if hasattr(artist, "get_array"):  # This targets pcolormesh objects
            artist.remove()

    plot_ds = sub_ds.isel(ensemble=ensemble_idx, time=0, lead_time=max(frame, 0))
    pc = ax.pcolormesh(
        sub_ds.lon,
        sub_ds.lat,
        plot_ds,
        transform=projection,
        cmap=colour_map,
        vmin=min_val,
        vmax=max_val,
    )

    ax.add_feature(cfeature.COASTLINE, lw=0.5)
    ax.add_feature(cfeature.RIVERS, lw=0.5)
    for track in tracks:
        ax.plot(
            track["lon"][: frame + 1],
            track["lat"][: frame + 1],
            transform=ccrs.PlateCarree(),
            color="lime",
            linewidth=1.0,
            alpha=1,
        )

    # Enforce the plotting region extent
    ax.set_extent([lon_min, lon_max, lat_min, lat_max], crs=ccrs.PlateCarree())

    if frame == -1:
        cbar = fig.colorbar(pc, extend="both", shrink=0.8, ax=ax)  # noqa: F841

    header = f"{base_name} {variable} lead time {frame*6}h"
    ax.set_title(header, fontsize=14)

    return pc


def animate(frame: int) -> plt.Artist:
    """Animation callback forwarding to ``make_frame``."""
    return make_frame(frame)


def first_frame() -> plt.Artist:
    """Initialisation callback rendering frame -1 (colourbar only)."""
    return make_frame(-1)


ani = animation.FuncAnimation(
    fig,
    animate,
    min(max_frames, sub_ds.sizes["lead_time"]),
    init_func=first_frame,
    blit=False,
    repeat=False,
    interval=1000 / fps,
)
plt.close("all")
ani

# %% [markdown]
# ### Step 4 (Optional): Save Animation
#
# Uncomment and run the cell below to save the animation as GIF in
# ``outputs_<base_name>/``.

# %%
# plt.close("all")
#
# # Recreate figure and animation
# cbar = None
# fig = plt.figure(figsize=(12, 8))
# ax = fig.add_subplot(1, 1, 1, projection=projection)
#
# ani = animation.FuncAnimation(
#     fig,
#     animate,
#     min(max_frames, sub_ds.sizes["lead_time"]),
#     init_func=first_frame,
#     blit=False,
#     repeat=False,
#     interval=1000 / fps,
# )
#
# os.makedirs(out_dir, exist_ok=True)
# ani.save(
#     os.path.join(out_dir, "tracks_n_fields_ani.gif"),
#     fps=fps,
#     savefig_kwargs={"bbox_inches": "tight", "pad_inches": 0.1},
# )
# plt.close(fig)
