project: 'reproduce_helene'
mode: 'reproduce_members'
model: 'fcn3'

reproduce_members: [
                    ['2024-09-24 00:00:00',  0, 2148531792],
                    ['2024-09-24 00:00:00',  8, 1342799488],
                    ['2024-09-24 00:00:00',  9, 1342799488],
                    ['2024-09-24 00:00:00', 12, 1968734508],
                   ]

n_steps: 28
ensemble_size: 16
batch_size: 2

data_source:
    _target_: earth2studio.data.NCAR_ERA5

store_type: "netcdf"
store_dir: "./outputs_${project}"
out_vars: ['msl', 'z300', 'z500', 'u10m', 'v10m']

cyclone_tracking:
    asynchronous: True
    vars: ['msl', 'u10m', 'v10m', 'z300', 'z500']
    detect_cmd: 'DetectNodes --verbosity 0 --mergedist 6 --closedcontourcmd _DIFF(z300,z500),-58.8,6.5,0;msl,200.,5.5,0 --searchbymin msl --outputcmd msl,min,0;_VECMAG(u10m,v10m),max,5;height,min,0'
    stitch_cmd: 'StitchNodes --in_fmt lon,lat,msl,wind_speed,height --range 8.0 --mintime 54h --maxgap 4 --out_file_format csv --threshold wind_speed,>=,10.,10;lat,<=,50.,10;lat,>=,-50.,10;height,<=,150.,10'
    orography_path: './orography.nc'
    keep_raw_data: False
    use_ram: True
    task_timeout_seconds: 120
    print_te_output: False

# hydra logs
hydra:
    job:
        name: ${project}
    run:
        dir: ${store_dir}/${project}_logs/${now:%Y-%m-%d_%H-%M-%S}
