# SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Bug Report
description: File a bug report for Earth2Studio
title: "🐛[BUG]: "
labels: ["bug", "? - Needs Triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help Earth2Studio and fill out this bug report!
        - By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/NVIDIA/earth2studio/blob/main/CONTRIBUTING.md)
        - You also confirm that you have searched the [open bugs](https://github.com/NVIDIA/earth2studio/issues) and have found no duplicates for this request

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Earth2Studio are you running?
      placeholder: "example: 0.6.0"
    validations:
      required: true

  - type: dropdown
    id: installation-method
    attributes:
      label: On which installation method(s) does this occur?
      multiple: true
      options:
        - pip
        - uv
        - source

  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: Please provide a complete and succinct description of the problem, logs and environment details.
      placeholder: XYZ occurred, I expected QRS results
    validations:
      required: true
