authors:
  ngeneva:
    name: Nicholas Geneva
    description: NVIDIA
    avatar: https://avatars.githubusercontent.com/u/5533524
    url: https://github.com/NickGeneva
  skhajehei:
    name: Sepideh Khajehei
    description: NVIDIA
    avatar: https://avatars.githubusercontent.com/u/47289741
    url: https://github.com/SepidehKhajehei
