# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from __future__ import annotations

import hashlib
import os
import pathlib
import shutil
import uuid
import zipfile
from collections.abc import Iterable
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone

import numpy as np
import pandas as pd
import pyarrow as pa
from loguru import logger

from earth2studio.data.utils import (
    _sync_async,
    async_retry,
    cancellable_to_thread,
    datasource_cache_dir,
    gather_with_concurrency,
    prep_data_inputs,
)
from earth2studio.data.utils_eumetsat import eumetsat_credentials
from earth2studio.lexicon import MeteosatLILexicon
from earth2studio.lexicon.base import E2STUDIO_SCHEMA
from earth2studio.utils.imports import (
    OptionalDependencyFailure,
    check_optional_dependencies,
)
from earth2studio.utils.time import normalize_time_tolerance
from earth2studio.utils.type import TimeArray, TimeTolerance, VariableArray

try:
    import eumdac
    import netCDF4
except ImportError:
    OptionalDependencyFailure("data")
    eumdac = None  # type: ignore[assignment]
    netCDF4 = None  # type: ignore[assignment]


# EUMETSAT Data Store collection id for each LI Level-2 pointed product
_COLLECTION_ID: dict[str, str] = {
    "LFL": "EO:EUM:DAT:0691",  # Lightning Flashes
    "LGR": "EO:EUM:DAT:0782",  # Lightning Groups
    "LEF": "EO:EUM:DAT:0690",  # Lightning Events Filtered
}

# NetCDF record dimension and per-record time variable of the flat products.
# LEF is nested (one group per optical head) and handled separately.
_FLAT_PRODUCT: dict[str, tuple[str, str]] = {
    "LFL": ("flashes", "flash_time"),
    "LGR": ("groups", "group_time"),
}

# Optical head groups of the LEF product, under the ``/data`` group
_LEF_HEADS = ("north", "south", "east", "west")

# Native record fields carried through to the output frame, per product. The
# synthetic ``_count`` field is generated by the source rather than read.
_PRODUCT_FIELDS: dict[str, tuple[str, ...]] = {
    "LFL": ("radiance", "flash_duration", "flash_footprint"),
    "LGR": ("radiance", "number_of_events"),
    "LEF": ("radiance",),
}

# Epoch of the LI ``seconds since 2000-01-01 00:00:00.0`` time encoding
_LI_EPOCH = np.datetime64("2000-01-01T00:00:00", "us")

# Archived products cover a 10 minute repeat cycle
_LI_GRANULE_DURATION = timedelta(seconds=600)

# Earliest LI Level-2 product in the EUMETSAT Data Store archive. Level-2 data
# was declared operational on 2024-10-31; earlier granules are pre-operational.
_LI_MIN_DATE = datetime(2024, 7, 4, 14, 0)


@dataclass(frozen=True)
class _MeteosatLIGranule:
    """One LI Level-2 product granule scheduled for download."""

    product: str
    product_id: str
    start: datetime
    end: datetime


@check_optional_dependencies()
class MeteosatLI:
    """EUMETSAT MTG-I LI Level-2 pointed lightning data source.

    Returns per-detection lightning observations from the Meteosat Third
    Generation (MTG) Lightning Imager (LI), served as point observations in a
    pandas DataFrame. The Level-2 processing clusters optical detections into a
    three-level hierarchy, each published as a separate EUMETSAT Data Store
    collection:

    - ``LFL`` Lightning Flashes, the coarsest level
      (``lightning_flash_*`` variables)
    - ``LGR`` Lightning Groups, detections clustered per integration frame
      (``lightning_group_*`` variables)
    - ``LEF`` Lightning Events Filtered, individual pixel detections that were
      retained by the flash clustering (``lightning_event_*`` variables)

    The collection a request reads from is determined by the requested
    variables, so only the products actually needed are downloaded. Each row
    carries the detection time, latitude/longitude and the requested
    measurement, with radiance reported in ``mW m-2 sr-1``. The
    ``lightning_*_count`` variables are a constant 1.0 per record, suitable
    for density aggregation.

    Groups and flashes also expose their footprint size as detector-pixel
    counts. ``lightning_group_footprint_pixels`` reads the LGR
    ``number_of_events`` field (each event is one contributing pixel), while
    ``lightning_flash_footprint_pixels`` reads the LFL ``flash_footprint``
    field. Events are individual pixels and have no event-level footprint
    variable.

    Parameters
    ----------
    lat_lon_bbox : tuple[float, float, float, float] | None, optional
        Bounding box ``(lat_min, lon_min, lat_max, lon_max)`` in degrees,
        applied at parse time. Accepts either the ``[-180, 180)`` or the
        ``[0, 360)`` longitude convention (auto-detected when
        ``lon_max >= 180``). ``None`` (default) returns the full disk. For
        example, Europe in the ``[-180, 180)`` convention is
        ``(35.0, -12.0, 60.0, 30.0)``.
    time_tolerance : TimeTolerance, optional
        Time tolerance window for selecting detections around each requested
        timestamp. Accepts a single value (symmetric window) or a tuple
        ``(lower, upper)`` for asymmetric windows, by default
        ``np.timedelta64(5, "m")``.
    cache : bool, optional
        Cache downloaded NetCDF files on local disk, by default True
    verbose : bool, optional
        Show download progress bar, by default True
    async_timeout : int, optional
        Total timeout in seconds for the entire fetch operation,
        by default 600
    async_workers : int, optional
        Maximum number of concurrent Data Store fetch tasks, by default 8
    retries : int, optional
        Number of retry attempts per failed fetch task with exponential
        backoff, by default 3

    Warning
    -------
    This is a remote data source and can potentially download a large amount of
    data to your local machine for large requests. The LEF product contains
    hundreds of thousands of detections per 10 minute granule; prefer
    ``lightning_flash_*`` variables and a bounded ``time_tolerance`` for
    large time windows.

    Note
    ----
    Requires EUMETSAT Data Store credentials. Set the following environment
    variables:

    - ``EUMETSAT_CONSUMER_KEY``: Your EUMETSAT API consumer key
    - ``EUMETSAT_CONSUMER_SECRET``: Your EUMETSAT API consumer secret

    Register at https://eoportal.eumetsat.int/ to obtain credentials.

    Note
    ----
    Output longitudes are normalised to ``[0, 360)`` (Earth2Studio
    convention). Detection times are decoded from each product's native
    ``seconds since 2000-01-01`` encoding, so sub-second precision is
    preserved. Products are archived as 10 minute granules; a granule is
    downloaded whenever it overlaps a requested tolerance window.

    Note
    ----
    Additional information on the data repository:

    - https://user.eumetsat.int/resources/user-guides/mtg-li-level-2-data-guide
    - https://data.eumetsat.int/product/EO:EUM:DAT:0691
    - https://user.eumetsat.int/s3/eup-strapi-media/MTG_LI_Level_2_Format_Specification_12c067c926.pdf

    Example
    -------
    ```python
    from datetime import datetime
    import numpy as np
    from earth2studio.data import MeteosatLI

    ds = MeteosatLI(
        lat_lon_bbox=(35.0, -12.0, 60.0, 30.0),  # Europe
        time_tolerance=np.timedelta64(5, "m"),
    )
    df = ds(
        datetime(2025, 6, 15, 12, 0),
        ["lightning_flash_radiance", "lightning_flash_count"],
    )

    ```
    Badges
    ------
    region:eu region:af dataclass:observation product:sat provider:eumetsat
    """

    SOURCE_ID = "earth2studio.data.meteosat_li"
    SCHEMA = pa.schema(
        [
            E2STUDIO_SCHEMA.field("time"),
            E2STUDIO_SCHEMA.field("lat"),
            E2STUDIO_SCHEMA.field("lon"),
            E2STUDIO_SCHEMA.field("observation"),
            E2STUDIO_SCHEMA.field("variable"),
            pa.field(
                "platform",
                pa.string(),
                metadata={"description": "MTG platform identifier (e.g. MTI1)"},
            ),
            pa.field(
                "flash_id",
                pa.uint32(),
                metadata={
                    "description": "LI Level-2 flash identifier. For group and "
                    "event records this is the id of the parent flash, so "
                    "detections can be clustered across the LFL/LGR/LEF hierarchy"
                },
            ),
        ]
    )

    def __init__(
        self,
        lat_lon_bbox: tuple[float, float, float, float] | None = None,
        time_tolerance: TimeTolerance = np.timedelta64(5, "m"),
        cache: bool = True,
        verbose: bool = True,
        async_timeout: int = 600,
        async_workers: int = 8,
        retries: int = 3,
    ) -> None:
        self._lat_lon_bbox = _normalize_lat_lon_bbox(lat_lon_bbox)

        lower, upper = normalize_time_tolerance(time_tolerance)
        self._tolerance_lower = pd.to_timedelta(lower).to_pytimedelta()
        self._tolerance_upper = pd.to_timedelta(upper).to_pytimedelta()

        self._cache = cache
        self._verbose = verbose
        self._async_workers = async_workers
        self._retries = retries
        self.async_timeout = async_timeout
        self._tmp_cache_hash: str | None = None

        self._consumer_key, self._consumer_secret = eumetsat_credentials()

    def __call__(
        self,
        time: datetime | list[datetime] | TimeArray,
        variable: str | list[str] | VariableArray,
        fields: str | list[str] | pa.Schema | None = None,
    ) -> pd.DataFrame:
        """Fetch LI lightning detections for a set of timestamps.

        Parameters
        ----------
        time : datetime | list[datetime] | TimeArray
            Timestamps to return detections for (UTC).
        variable : str | list[str] | VariableArray
            Variable ids defined in
            :py:class:`earth2studio.lexicon.MeteosatLILexicon`.
        fields : str | list[str] | pa.Schema | None, optional
            Output column subset. ``None`` (default) returns all schema
            fields.

        Returns
        -------
        pd.DataFrame
            Detection-level lightning observations with columns matching the
            resolved schema.
        """
        try:
            df = _sync_async(
                self.fetch, time, variable, fields, timeout=self.async_timeout
            )
        finally:
            if not self._cache:
                shutil.rmtree(self.cache, ignore_errors=True)
        return df

    async def fetch(
        self,
        time: datetime | list[datetime] | TimeArray,
        variable: str | list[str] | VariableArray,
        fields: str | list[str] | pa.Schema | None = None,
    ) -> pd.DataFrame:
        """Async function to fetch LI lightning detections.

        Parameters
        ----------
        time : datetime | list[datetime] | TimeArray
            Timestamps to return detections for (UTC).
        variable : str | list[str] | VariableArray
            Variable ids defined in :py:class:`MeteosatLILexicon`.
        fields : str | list[str] | pa.Schema | None, optional
            Output column subset. ``None`` (default) returns all schema
            fields.

        Returns
        -------
        pd.DataFrame
            Detection-level lightning observations.
        """
        time_list, variable_list = prep_data_inputs(time, variable)
        self._validate_time(time_list)

        # Resolve each variable to its (product, field) pair up front so an
        # unknown variable fails before anything is downloaded
        resolved: dict[str, tuple[str, str]] = {}
        for v in variable_list:
            if v not in MeteosatLILexicon.VOCAB:
                raise KeyError(
                    f"Variable id {v!r} not found in MeteosatLILexicon. "
                    f"Available: {list(MeteosatLILexicon.VOCAB)}"
                )
            key, _ = MeteosatLILexicon[v]  # type: ignore[misc]
            product, field = key.split("::")
            resolved[v] = (product, field)

        schema = self.resolve_fields(fields)
        pathlib.Path(self.cache).mkdir(parents=True, exist_ok=True)

        products = sorted({p for (p, _) in resolved.values()})
        granules = await self._discover_granules(time_list, products)
        logger.info(
            f"[{self.SOURCE_ID}] discovered {len(granules)} LI granules across "
            f"{len(products)} product(s) for {len(time_list)} requested times"
        )

        coros = [
            async_retry(
                self._fetch_granule,
                granule,
                retries=self._retries,
                backoff=2.0,
                exceptions=(OSError, IOError, TimeoutError, ConnectionError),
            )
            for granule in granules
        ]
        paths = await gather_with_concurrency(
            coros,
            max_workers=self._async_workers,
            desc="Fetching MTG LI L2 granules",
            verbose=(not self._verbose),
        )

        return self._compile_dataframe(
            [(g, p) for g, p in zip(granules, paths) if p is not None],
            time_list,
            variable_list,
            resolved,
            schema,
        )

    async def _discover_granules(
        self, time_list: list[datetime], products: list[str]
    ) -> list[_MeteosatLIGranule]:
        """Search the Data Store for granules overlapping the requested windows.

        Per-time tolerance windows are merged into a minimal set of intervals
        before searching so that a long list of closely spaced timestamps costs
        one catalogue query per product rather than one per timestamp.
        """
        windows = [
            (t + self._tolerance_lower, t + self._tolerance_upper) for t in time_list
        ]
        merged = _merge_windows(windows, _LI_GRANULE_DURATION)

        jobs = [(product, lo, hi) for product in products for (lo, hi) in merged]
        listings = await gather_with_concurrency(
            [self._search_window(product, lo, hi) for (product, lo, hi) in jobs],
            max_workers=self._async_workers,
            desc="Searching MTG LI L2 catalogue",
            verbose=(not self._verbose),
        )

        granules: dict[tuple[str, str], _MeteosatLIGranule] = {}
        for entries in listings:
            for granule in entries:
                granules.setdefault((granule.product, granule.product_id), granule)
        return sorted(granules.values(), key=lambda g: (g.product, g.start))

    async def _search_window(
        self, product: str, start: datetime, end: datetime
    ) -> list[_MeteosatLIGranule]:
        """Search one product collection over a single time interval."""

        def _search() -> list[_MeteosatLIGranule]:
            datastore = self._datastore()
            collection = datastore.get_collection(_COLLECTION_ID[product])
            return [
                _MeteosatLIGranule(
                    product=product,
                    product_id=str(p),
                    start=p.sensing_start,
                    end=p.sensing_end,
                )
                for p in collection.search(dtstart=start, dtend=end)
            ]

        return await async_retry(
            cancellable_to_thread,
            _search,
            timeout=120.0,
            retries=self._retries,
            backoff=2.0,
            exceptions=(OSError, IOError, TimeoutError, ConnectionError),
        )

    async def _fetch_granule(self, granule: _MeteosatLIGranule) -> str | None:
        """Download one granule and cache its BODY NetCDF.

        Products are served as zip archives; only the BODY member is kept. The
        zip is fetched rather than the BODY entry alone because the archive
        transfers compressed and is several times smaller on the wire.
        """
        cache_path = self._cache_path(granule)
        if pathlib.Path(cache_path).is_file():
            return cache_path

        def _download() -> str | None:
            datastore = self._datastore()
            product = datastore.get_product(
                _COLLECTION_ID[granule.product], granule.product_id
            )
            body = [
                e
                for e in product.entries
                if "CHK-BODY" in os.path.basename(e) and e.endswith(".nc")
            ]
            if not body:
                logger.warning(
                    f"No BODY NetCDF entry in LI granule {granule.product_id}, skipping"
                )
                return None

            zip_path = cache_path + f".{uuid.uuid4().hex[:8]}.zip"
            try:
                with product.open() as stream, open(zip_path, "wb") as f:
                    shutil.copyfileobj(stream, f)
                if not zipfile.is_zipfile(zip_path):
                    raise RuntimeError(
                        f"Downloaded LI product {granule.product_id} is not a "
                        f"valid zip archive ({os.path.getsize(zip_path)} bytes)"
                    )
                tmp_path = cache_path + f".{uuid.uuid4().hex[:8]}.tmp"
                with zipfile.ZipFile(zip_path, "r") as zf:
                    member = next(
                        (
                            n
                            for n in zf.namelist()
                            if os.path.basename(n) == os.path.basename(body[0])
                        ),
                        None,
                    )
                    if member is None:
                        raise FileNotFoundError(
                            f"BODY entry {body[0]} missing from LI product "
                            f"{granule.product_id} archive"
                        )
                    with zf.open(member) as src, open(tmp_path, "wb") as dst:
                        shutil.copyfileobj(src, dst)
                # Publish atomically so a concurrent reader never sees a
                # partially written NetCDF
                os.replace(tmp_path, cache_path)
            finally:
                if os.path.isfile(zip_path):
                    os.remove(zip_path)
            return cache_path

        return await cancellable_to_thread(_download, timeout=300.0)

    def _compile_dataframe(
        self,
        granules: list[tuple[_MeteosatLIGranule, str]],
        time_list: list[datetime],
        variable_list: list[str],
        resolved: dict[str, tuple[str, str]],
        schema: pa.Schema,
    ) -> pd.DataFrame:
        """Parse each cached granule once, filter per requested time, and emit
        one long-format DataFrame across all variables and times.
        """
        # Parse each granule a single time, keyed by product so a requested
        # time only scans the products it needs
        records: dict[str, list[pd.DataFrame]] = {}
        for granule, path in granules:
            if not pathlib.Path(path).is_file():
                continue
            parsed = self._parse_granule(path, granule.product, self._lat_lon_bbox)
            if parsed is None or parsed.empty:
                continue
            records.setdefault(granule.product, []).append(parsed)

        if not records:
            return self._empty_result(schema)

        frames: list[pd.DataFrame] = []
        for t in time_list:
            tmin = pd.Timestamp(t + self._tolerance_lower)
            tmax = pd.Timestamp(t + self._tolerance_upper)
            for v in variable_list:
                product, field = resolved[v]
                for parsed in records.get(product, []):
                    mask = (parsed["time"] >= tmin) & (parsed["time"] <= tmax)
                    if not mask.any():
                        continue
                    window = parsed.loc[mask]
                    sub = window[["time", "lat", "lon", "platform", "flash_id"]].copy()
                    if field == "_count":
                        sub["observation"] = np.float32(1.0)
                    else:
                        sub["observation"] = window[field].astype(np.float32)
                    sub["variable"] = v
                    frames.append(sub)

        if not frames:
            return self._empty_result(schema)

        df = pd.concat(frames, ignore_index=True)
        # Normalise longitude from LI's [-180, 180) to Earth2Studio's [0, 360)
        df["lon"] = (df["lon"].astype(np.float32) + 360.0) % 360.0
        df["lat"] = df["lat"].astype(np.float32)
        df.attrs["source"] = self.SOURCE_ID
        return df[[name for name in schema.names if name in df.columns]]

    def _empty_result(self, schema: pa.Schema) -> pd.DataFrame:
        empty = pd.DataFrame(
            {name: pd.Series(dtype="object") for name in self.SCHEMA.names}
        )
        empty.attrs["source"] = self.SOURCE_ID
        return empty[[name for name in schema.names if name in empty.columns]]

    def _datastore(self) -> eumdac.DataStore:
        """Build an authenticated Data Store handle.

        A fresh access token is minted per blocking call rather than cached on
        the instance: tokens expire, and ``eumdac`` handles are not safe to
        share across the worker threads that drive the downloads.
        """
        token = eumdac.AccessToken(
            credentials=(self._consumer_key, self._consumer_secret)
        )
        return eumdac.DataStore(token)

    def _cache_path(self, granule: _MeteosatLIGranule) -> str:
        sha = hashlib.sha256(
            f"{granule.product}/{granule.product_id}".encode()
        ).hexdigest()
        return os.path.join(self.cache, sha + ".nc")

    @classmethod
    def _validate_time(cls, times: Iterable[datetime]) -> None:
        """Verify date times fall within the LI Level-2 archive window.

        Parameters
        ----------
        times : Iterable[datetime]
            UTC timestamps to validate

        Raises
        ------
        ValueError
            If any time is before the archive start or in the future
        """
        for t in times:
            if t < _LI_MIN_DATE:
                raise ValueError(
                    f"Requested datetime {t} is earlier than the MTG LI "
                    f"Level-2 archive start ({_LI_MIN_DATE.isoformat()})."
                )
            now_utc = datetime.now(timezone.utc).replace(tzinfo=None)
            if t > now_utc + timedelta(hours=1):
                raise ValueError(
                    f"Requested datetime {t} is in the future; the MTG LI "
                    f"Level-2 archive has no entries beyond now."
                )

    @classmethod
    def _parse_granule(
        cls,
        path: str,
        product: str,
        lat_lon_bbox: tuple[float, float, float, float] | None,
    ) -> pd.DataFrame | None:
        """Parse one LI Level-2 BODY NetCDF into a flat detections DataFrame.

        ``LFL`` and ``LGR`` store one flat record array; ``LEF`` nests one
        record array per optical head under ``/data``, which are concatenated
        here. Returns ``None`` when the granule holds no detections or all
        detections fall outside ``lat_lon_bbox``.
        """
        with netCDF4.Dataset(path) as ds:
            platform = str(getattr(ds, "platform", ""))
            if product == "LEF":
                parts = [
                    cls._read_records(
                        ds[f"/data/{head}"],
                        _PRODUCT_FIELDS[product],
                        time_var=None,
                    )
                    for head in _LEF_HEADS
                    if head in ds["/data"].groups
                ]
                parts = [p for p in parts if p is not None]
                if not parts:
                    return None
                frame = pd.concat(parts, ignore_index=True)
            else:
                record_dim, time_var = _FLAT_PRODUCT[product]
                if ds.dimensions[record_dim].size == 0:
                    return None
                frame = cls._read_records(
                    ds, _PRODUCT_FIELDS[product], time_var=time_var
                )
                if frame is None:
                    return None

        frame["platform"] = platform

        if lat_lon_bbox is not None:
            lat_min, lon_min, lat_max, lon_max = lat_lon_bbox
            mask = (
                (frame["lat"] >= lat_min)
                & (frame["lat"] <= lat_max)
                & (frame["lon"] >= lon_min)
                & (frame["lon"] <= lon_max)
            )
            if not mask.any():
                return None
            frame = frame.loc[mask].reset_index(drop=True)

        return frame

    @staticmethod
    def _read_records(
        group: netCDF4.Dataset,
        fields: tuple[str, ...],
        time_var: str | None,
    ) -> pd.DataFrame | None:
        """Read the record arrays of one flat NetCDF group.

        Parameters
        ----------
        group : netCDF4.Dataset
            Dataset or group holding the record variables
        fields : tuple[str, ...]
            Native measurement variables to carry through
        time_var : str | None
            Name of the per-record time variable, in ``seconds since
            2000-01-01``. When ``None`` the LEF encoding is used instead: a
            scalar ``epoch_time`` plus a per-record ``time_offset`` in seconds.

        Returns
        -------
        pd.DataFrame | None
            Frame with ``time``/``lat``/``lon``/``flash_id`` and one column per
            requested field, or ``None`` when the group holds no usable
            records.

        Note
        ----
        Optical head groups can be padded with placeholder records whose
        coordinates and times are the NetCDF fill value (masked on read).
        These are dropped: a fill-valued time is ~1e37 s, which overflows
        the microsecond integer cast and would otherwise yield a garbage
        timestamp that lands in or out of the tolerance window at random.
        """
        if "latitude" not in group.variables:
            return None

        lat = _read_masked(group.variables["latitude"][:])
        if lat.size == 0:
            return None
        lon = _read_masked(group.variables["longitude"][:])

        if time_var is not None:
            seconds = _read_masked(group.variables[time_var][:])
        else:
            epoch = float(np.asarray(group.variables["epoch_time"][:]).reshape(()))
            seconds = epoch + _read_masked(group.variables["time_offset"][:])

        valid = np.isfinite(lat) & np.isfinite(lon) & np.isfinite(seconds)
        if not valid.any():
            return None
        lat, lon, seconds = lat[valid], lon[valid], seconds[valid]

        # Round to microseconds, the resolution of the output timestamps
        times = _LI_EPOCH + np.round(seconds * 1e6).astype("timedelta64[us]")

        data: dict[str, np.ndarray] = {
            "time": pd.to_datetime(times),
            "lat": lat.astype(np.float32),
            "lon": lon.astype(np.float32),
            "flash_id": np.asarray(group.variables["flash_id"][:], dtype=np.uint32)[
                valid
            ],
        }
        for field in fields:
            # Measurements keep NaN for fill values rather than dropping the
            # record, so a detection missing one field still reports the others
            data[field] = _read_masked(group.variables[field][:])[valid].astype(
                np.float32
            )
        return pd.DataFrame(data)

    @property
    def cache(self) -> str:
        """Local cache directory for this data source."""
        if not self._cache and self._tmp_cache_hash is None:
            self._tmp_cache_hash = uuid.uuid4().hex[:8]
        return datasource_cache_dir("meteosat_li", self._cache, self._tmp_cache_hash)

    @classmethod
    def available(cls, time: datetime | np.datetime64) -> bool:
        """Check whether data is available for a given time.

        Offline check against the LI Level-2 archive window.

        Parameters
        ----------
        time : datetime | np.datetime64
            Date-time to check.

        Returns
        -------
        bool
            Whether the requested date time is available.
        """
        if isinstance(time, np.datetime64):
            time = time.astype("datetime64[ns]").astype("datetime64[us]").item()
        try:
            cls._validate_time([time])
        except ValueError:
            return False
        return True

    @classmethod
    def resolve_fields(cls, fields: str | list[str] | pa.Schema | None) -> pa.Schema:
        """Resolve a ``fields`` selector into a validated PyArrow schema.

        Parameters
        ----------
        fields : str | list[str] | pa.Schema | None
            Column selector. ``None`` returns the full class schema.

        Returns
        -------
        pa.Schema
            Schema of the selected columns.
        """
        if fields is None:
            return cls.SCHEMA
        if isinstance(fields, str):
            fields = [fields]
        if isinstance(fields, pa.Schema):
            for f in fields:
                if f.name not in cls.SCHEMA.names:
                    raise KeyError(
                        f"Field '{f.name}' not in {cls.__name__} SCHEMA. "
                        f"Available: {cls.SCHEMA.names}"
                    )
                expected = cls.SCHEMA.field(f.name).type
                if f.type != expected:
                    raise TypeError(
                        f"Field '{f.name}' has type {f.type}, expected "
                        f"{expected} from class SCHEMA"
                    )
            return fields
        selected = []
        for name in fields:
            if name not in cls.SCHEMA.names:
                raise KeyError(
                    f"Field '{name}' not in {cls.__name__} SCHEMA. "
                    f"Available: {cls.SCHEMA.names}"
                )
            selected.append(cls.SCHEMA.field(name))
        return pa.schema(selected)


def _read_masked(values: np.ndarray) -> np.ndarray:
    """Read a NetCDF record array as float64 with fill values as NaN.

    netCDF4 returns masked arrays for variables carrying a ``_FillValue``.
    A plain ``np.asarray`` drops the mask and exposes the raw fill (~1e37
    for floats), so masked entries are converted to NaN here and the caller
    decides whether to drop or propagate them.

    Parameters
    ----------
    values : np.ndarray
        Array (typically masked) as returned by ``netCDF4.Variable[:]``.

    Returns
    -------
    np.ndarray
        Float64 array with masked and non-finite entries set to NaN.
    """
    masked = np.ma.masked_invalid(np.ma.asarray(values).astype(np.float64))
    return np.ma.filled(masked, np.nan)


def _merge_windows(
    windows: list[tuple[datetime, datetime]], pad: timedelta
) -> list[tuple[datetime, datetime]]:
    """Merge overlapping time windows after widening each by ``pad``.

    The lower bound is widened by one granule duration so that a granule
    which *starts* before the window but still covers it is returned by the
    catalogue search.

    Parameters
    ----------
    windows : list[tuple[datetime, datetime]]
        ``(start, end)`` intervals, in any order.
    pad : timedelta
        Amount to widen the lower bound of each interval by.

    Returns
    -------
    list[tuple[datetime, datetime]]
        Disjoint intervals covering the union of the padded inputs.
    """
    padded = sorted((lo - pad, hi) for (lo, hi) in windows)
    merged: list[tuple[datetime, datetime]] = []
    for lo, hi in padded:
        if merged and lo <= merged[-1][1]:
            merged[-1] = (merged[-1][0], max(merged[-1][1], hi))
        else:
            merged.append((lo, hi))
    return merged


def _normalize_lat_lon_bbox(
    lat_lon_bbox: tuple[float, float, float, float] | None,
) -> tuple[float, float, float, float] | None:
    """Validate a ``(lat_min, lon_min, lat_max, lon_max)`` box.

    Accepts either the ``[-180, 180)`` or the ``[0, 360)`` longitude
    convention and normalises to the native LI ``[-180, 180)`` convention used
    by the on-disk detection coordinates.

    Parameters
    ----------
    lat_lon_bbox : tuple[float, float, float, float] | None
        Bounding box in degrees, or ``None``.

    Returns
    -------
    tuple[float, float, float, float] | None
        Normalised bounding box, or ``None`` when the input was ``None``.
    """
    if lat_lon_bbox is None:
        return None
    lat_min, lon_min, lat_max, lon_max = lat_lon_bbox
    if lat_min >= lat_max or lon_min >= lon_max:
        raise ValueError(
            "lat_lon_bbox bounds must be "
            "(lat_min < lat_max, lon_min < lon_max); "
            f"got {lat_lon_bbox}"
        )
    if lon_max >= 180.0:
        lon_min = ((lon_min + 180.0) % 360.0) - 180.0
        lon_max = ((lon_max + 180.0) % 360.0) - 180.0
        if lon_min >= lon_max:
            raise ValueError(
                "lat_lon_bbox crosses the antimeridian after normalising from "
                f"[0, 360) to [-180, 180); split it into two boxes. "
                f"Got {lat_lon_bbox}."
            )
    return (lat_min, lon_min, lat_max, lon_max)
