project: 'hens'
random_seed: 377778

start_times: ["2023-02-01"]
#ic_block_start: "2022-02-08"
#ic_block_end: "2022-02-09"
#ic_block_step: 24

nsteps: 20          # number of forecasting steps
nensemble: 2       # ensemble size per checkpoint
batch_size: 2      # inference batch size
torch_use_deterministic_algorithms: False # has impact on performace, in many cases results can be reproduced also if it is set to False
#batch_ids_reproduce: [3] # select specifc batchs that you want to run to reproduce certain runs

forecast_model:
    architecture: earth2studio.models.px.SFNO   # forecast model class
    package: hens_model_registry # TODO: Rename this to registry
    max_num_checkpoints: 29  # max number of checkpoints which will be used

diagnostic_models:
    r:
        _target_: earth2studio.enterprise.models.dx.DerivedVariables
        calculation_name: 'r_from_q_t_sp'
        levels: [850,500]
    ws:
        _target_: earth2studio.enterprise.models.dx.DerivedVariables
        calculation_name: 'ws_from_u_v'
        levels: [850,500,'10m']
    precipitation:
        architecture: earth2studio.models.dx.PrecipitationAFNO

    vpd:
        _target_: earth2studio.enterprise.models.dx.DerivedVariables
        calculation_name: 'vpd_from_r_t'
        levels: [850,500]


cyclone_tracking:
    out_dir: 'outputs'       # path to which write cyclone tracks


perturbation:
    method: 'hcbv'             # perturbation method
    integration_steps: 3      # integration steps in vector breeding
    noise_amplification: .35   # amplification of noise
    skill_path : hens_model_registry/d2m_sfno_linear_74chq_sc2_layers8_edim620_wstgl2-epoch70_seed16.nc
    perturbed_var: ['z500']



data_source:
    _target_: earth2studio.data.ARCO


file_output:
    path: 'outputs'       # directory to which outfiles are written
    output_vars: ['t2m', 'u10m', 't850', 'z500','vpd850','vpd500','r500','r850','ws10m','ws850','ws500','ws10m','msl','sp']
    thread_io: False      # write out in seperate thread (needs further testing)
    format:               # io backend class
        _target_: earth2studio.io.KVBackend
        # _target_: earth2studio.io.XarrayBackend
    cropboxes:
        Europe:
            lat_min: 33
            lat_max: 70
            lon_min: -20
            lon_max: 40
        Japan:
            lat_min: 29
            lat_max: 46
            lon_min: 125
            lon_max: 146
