[project]
name = "e2s.recipe"
version = "0.1.0"
description = "Recipe Template"
readme = "README.md"
requires-python = ">=3.10"
authors = [
  { name="NVIDIA PhysicsNeMo Team" },
]
dependencies = [
    "earth2studio",
    "omegaconf",
]

[project.urls]
Homepage = "https://github.com/NVIDIA/earth2studio"
Documentation = "https://nvidia.github.io/earth2studio"
Issues = "https://github.com/NVIDIA/earth2studio/issues"
Changelog = "https://github.com/NVIDIA/earth2studio/blob/main/CHANGELOG.md"

[tool.uv.sources]
earth2studio = { git = "https://github.com/NVIDIA/earth2studio", rev = "0.6.0" }
omegaconf = { git = "https://github.com/omry/omegaconf.git" }

[tool.hatch.build.targets.sdist]
include = ["src/**/*.py"]
exclude = []
