# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate blog listing pages from Earth2Studio blog posts.

Zensical does not yet ship a blog plugin, so the blog index, archive, and
category pages are generated from post front matter as a pre-build step (the
same way ``generate_blog_rss.py`` generates the RSS feed). This removes the
need to hand-maintain listings whenever a post is added.

Zensical also has no author byline on blog posts. The byline is rendered by a
theme override (``docs/overrides/partials/content.html``) that imports a small
Minijinja macro generated here from ``docs/blog/.authors.yml``, so authors stay
defined in exactly one place.

Generated files (git-ignored):

* ``docs/blog/index.md``
* ``docs/blog/archive.md``
* ``docs/blog/categories.md``
* ``docs/blog/categories/<slug>.md``
* ``docs/overrides/partials/_blog_byline.html``
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path

import yaml

DOCS_ROOT = Path(__file__).resolve().parent
BLOG_DIR = DOCS_ROOT / "blog"
POSTS_DIR = BLOG_DIR / "posts"
CATEGORIES_DIR = BLOG_DIR / "categories"
CATEGORY_META = BLOG_DIR / ".categories.yml"
AUTHORS_FILE = BLOG_DIR / ".authors.yml"
BYLINE_PARTIAL = DOCS_ROOT / "overrides" / "partials" / "_blog_byline.html"
EXCERPT_SPLIT = "<!-- more -->"

BLOG_INTRO = "Earth-2 Product and Engineering Blog Posts and Updates."
BLOG_SUBSCRIBE_BUTTON = (
    "[:fontawesome-solid-rss: Subscribe via RSS](feed.xml)"
    "{ .e2s-blog-subscribe }"
)
DEFAULT_CATEGORY_DESCRIPTION = "Posts filed under this topic."
GENERATED_NOTICE = (
    "<!-- This file is generated by docs/generate_blog_index.py. "
    "Do not edit by hand. -->"
)


@dataclass(frozen=True)
class BlogPost:
    """A published blog post used to build listing pages."""

    title: str
    description: str
    date: date
    slug: str
    categories: tuple[str, ...]


def main() -> None:
    """Generate the blog index, archive, and category pages."""
    posts = _load_posts()
    category_meta = _load_category_meta()

    _write(BLOG_DIR / "index.md", _render_index(posts))
    _write(BLOG_DIR / "archive.md", _render_archive(posts))
    _write(BLOG_DIR / "categories.md", _render_categories(posts, category_meta))

    CATEGORIES_DIR.mkdir(parents=True, exist_ok=True)
    seen: set[str] = set()
    for name in _categories(posts):
        slug = _slugify(name)
        seen.add(f"{slug}.md")
        _write(
            CATEGORIES_DIR / f"{slug}.md",
            _render_category_page(name, posts, category_meta),
        )
    _prune_categories(seen)

    _write(BYLINE_PARTIAL, _render_byline_partial(_load_authors()))


def _load_posts() -> list[BlogPost]:
    """Return published posts newest-first."""
    posts: list[BlogPost] = []
    if not POSTS_DIR.is_dir():
        return posts

    for path in sorted(POSTS_DIR.glob("*.md")):
        post = _parse_post(path)
        if post is not None:
            posts.append(post)

    posts.sort(key=lambda item: (item.date, item.slug), reverse=True)
    return posts


def _load_category_meta() -> dict[str, str]:
    """Return optional ``category name -> description`` overrides."""
    if not CATEGORY_META.is_file():
        return {}
    try:
        data = yaml.safe_load(CATEGORY_META.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError:
        return {}
    if not isinstance(data, dict):
        return {}
    return {str(key): str(value) for key, value in data.items()}


def _load_authors() -> dict[str, dict[str, str]]:
    """Return ``author id -> {name, url, avatar}`` from ``.authors.yml``."""
    if not AUTHORS_FILE.is_file():
        return {}
    try:
        data = yaml.safe_load(AUTHORS_FILE.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError:
        return {}
    authors = data.get("authors") if isinstance(data, dict) else None
    if not isinstance(authors, dict):
        return {}

    result: dict[str, dict[str, str]] = {}
    for author_id, info in authors.items():
        if not isinstance(info, dict):
            continue
        result[str(author_id)] = {
            "name": str(info.get("name") or author_id),
            "url": str(info.get("url") or ""),
            "avatar": str(info.get("avatar") or ""),
        }
    return result


def _render_byline_partial(authors: dict[str, dict[str, str]]) -> str:
    """Return a Minijinja macro that renders a blog post byline.

    Zensical has no blog plugin, so the author byline is rendered by a theme
    override (``docs/overrides/partials/content.html``). That template imports
    this generated macro, which bakes in the ``.authors.yml`` data so author
    identifiers resolve to a name, link, and avatar. Keeping the data source in
    ``.authors.yml`` means authors are defined in exactly one place.
    """
    authors_literal = json.dumps(authors, ensure_ascii=False, sort_keys=True)
    return f"""{{#- Generated by docs/generate_blog_index.py. Do not edit. -#}}
{{% macro e2s_byline(page) -%}}
{{%- set authors = {authors_literal} -%}}
<div class="e2s-byline">
{{%- if page.meta.authors -%}}
<span class="e2s-byline__authors">
{{%- for aid in page.meta.authors -%}}
{{%- set a = authors[aid] -%}}
{{%- if a -%}}
<a class="e2s-byline__author" href="{{{{ a.url }}}}">
{{%- if a.avatar %}}<img class="e2s-byline__avatar" src="{{{{ a.avatar }}}}" alt="">{{% endif -%}}
<span>{{{{ a.name }}}}</span></a>
{{%- else -%}}
<span class="e2s-byline__author"><span>{{{{ aid }}}}</span></span>
{{%- endif -%}}
{{%- endfor -%}}
</span>
{{%- endif -%}}
{{%- if page.meta.date -%}}
{{%- set d = page.meta.date | string -%}}
{{%- set months = ["", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"] -%}}
<time class="e2s-byline__date" datetime="{{{{ d }}}}">{{{{ months[d[5:7] | int] }}}} {{{{ d[8:10] | int }}}}, {{{{ d[0:4] }}}}</time>
{{%- endif -%}}
{{%- if page.meta.categories -%}}
<span class="e2s-byline__cats">
{{%- for c in page.meta.categories -%}}
<a class="e2s-byline__cat" href="{{{{ ('blog/categories/' ~ (c | lower | replace(' ', '-')) ~ '/') | url }}}}">{{{{ c }}}}</a>
{{%- endfor -%}}
</span>
{{%- endif -%}}
</div>
{{%- endmacro %}}
"""


def _parse_post(path: Path) -> BlogPost | None:
    """Return a published post, or ``None`` for drafts and undated files."""
    text = path.read_text(encoding="utf-8")
    meta, body = _split_front_matter(text)
    if meta.get("draft") is True:
        return None

    published = _parse_date(meta.get("date"))
    if published is None:
        return None

    title = str(meta.get("title") or "").strip() or _heading_title(body) or path.stem
    description = str(meta.get("description") or "").strip() or _excerpt(body)
    categories = tuple(
        str(item).strip() for item in meta.get("categories", []) if str(item).strip()
    )
    return BlogPost(
        title=title,
        description=description,
        date=published,
        slug=path.stem,
        categories=categories,
    )


def _split_front_matter(text: str) -> tuple[dict[str, object], str]:
    """Split YAML front matter from Markdown body."""
    if not text.startswith("---"):
        return {}, text

    parts = text.split("---", 2)
    if len(parts) < 3:
        return {}, text

    try:
        meta = yaml.safe_load(parts[1]) or {}
    except yaml.YAMLError:
        meta = {}
    if not isinstance(meta, dict):
        meta = {}
    return meta, parts[2]


def _parse_date(value: object) -> date | None:
    """Parse a blog ``date`` field from front matter."""
    if isinstance(value, datetime):
        return value.date()
    if isinstance(value, date):
        return value
    if isinstance(value, dict):
        return _parse_date(value.get("created") or value.get("date"))
    if isinstance(value, str):
        try:
            return date.fromisoformat(value[:10])
        except ValueError:
            return None
    return None


def _heading_title(body: str) -> str:
    """Return the first Markdown heading in ``body``."""
    for line in body.splitlines():
        stripped = line.strip()
        if stripped.startswith("#"):
            return stripped.lstrip("#").strip()
    return ""


def _excerpt(body: str) -> str:
    """Return a plain-text excerpt for listing descriptions."""
    if EXCERPT_SPLIT in body:
        body = body.split(EXCERPT_SPLIT, 1)[0]

    lines: list[str] = []
    for line in body.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith(("#", "!", "```", ":::")):
            continue
        lines.append(stripped)

    text = " ".join(lines)
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    text = re.sub(r"[*`_]", "", text)
    return re.sub(r"\s+", " ", text).strip()


def _categories(posts: list[BlogPost]) -> list[str]:
    """Return category names sorted alphabetically (case-insensitive)."""
    names = {name for post in posts for name in post.categories}
    return sorted(names, key=str.lower)


def _slugify(name: str) -> str:
    """Return a filename-safe slug for a category name."""
    slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    return slug or "uncategorized"


def _format_date(value: date) -> str:
    """Return a human-readable date such as ``August 20, 2026``."""
    return f"{value.strftime('%B')} {value.day}, {value.year}"


def _badges(post: BlogPost) -> str:
    """Return clickable category badges linking to each category page."""
    return " ".join(
        f"[{name}](categories/{_slugify(name)}.md){{ .e2s-cat-badge }}"
        for name in post.categories
    )


def _render_index(posts: list[BlogPost]) -> str:
    """Return the blog overview page."""
    lines = [
        GENERATED_NOTICE,
        "",
        "# Blog",
        "",
        BLOG_INTRO,
        "",
        BLOG_SUBSCRIBE_BUTTON,
        "",
        "## Latest Updates",
    ]
    if not posts:
        lines += ["", "_No posts yet._"]
    for post in posts:
        link = f"posts/{post.slug}.md"
        meta = " · ".join(filter(None, [_badges(post), _format_date(post.date)]))
        lines += [
            "",
            f"### [{post.title}]({link})",
            "",
            meta,
            "",
            post.description,
            "",
            f"[Read post]({link})",
        ]
    return "\n".join(lines) + "\n"


def _render_archive(posts: list[BlogPost]) -> str:
    """Return the archive page grouped by year, newest first."""
    lines = [GENERATED_NOTICE, "", "# Archive"]
    if not posts:
        lines += ["", "_No posts yet._"]
    years = sorted({post.date.year for post in posts}, reverse=True)
    for year in years:
        lines += ["", f"## {year}", ""]
        for post in posts:
            if post.date.year != year:
                continue
            link = f"posts/{post.slug}.md"
            lines.append(f"- [{post.title}]({link}) · {_format_date(post.date)}")
    return "\n".join(lines) + "\n"


def _render_categories(posts: list[BlogPost], meta: dict[str, str]) -> str:
    """Return the categories overview page."""
    lines = [GENERATED_NOTICE, "", "# Categories", "", "Browse posts by topic."]
    for name in _categories(posts):
        slug = _slugify(name)
        description = meta.get(name, DEFAULT_CATEGORY_DESCRIPTION)
        lines += [
            "",
            f"## [{name}](categories/{slug}.md)",
            "",
            description,
            "",
            f"[View posts](categories/{slug}.md)",
        ]
    return "\n".join(lines) + "\n"


def _render_category_page(
    name: str, posts: list[BlogPost], meta: dict[str, str]
) -> str:
    """Return a single category listing page."""
    description = meta.get(name, DEFAULT_CATEGORY_DESCRIPTION)
    lines = [GENERATED_NOTICE, "", f"# {name}", "", description, ""]
    for post in posts:
        if name not in post.categories:
            continue
        link = f"../posts/{post.slug}.md"
        lines.append(f"- [{post.title}]({link}) · {_format_date(post.date)}")
    return "\n".join(lines) + "\n"


def _prune_categories(keep: set[str]) -> None:
    """Remove stale generated category pages no longer backed by a post."""
    if not CATEGORIES_DIR.is_dir():
        return
    for path in CATEGORIES_DIR.glob("*.md"):
        if path.name not in keep:
            path.unlink()


def _write(path: Path, content: str) -> None:
    """Write ``content`` to ``path``."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
