project: 'helene'

start_times: ["2024-09-24 12:00:00"]
nsteps: 2 # 40          # number of forecasting steps
nensemble: 2 # 32       # ensemble size per checkpoint
batch_size: 2      # inference batch size

forecast_model:
    architecture: earth2studio.models.px.SFNO   # forecast model class
    package: '/media/mkoch/9ee63bf8-5a14-4872-86f2-7f16b120269b/hens_data/hens_checkpoints'
    max_num_checkpoints: 1 # max number of checkpoints which will be used

perturbation:
    _target_: hens_perturbation.HENSPerturbation
    _partial_: True
    skill_path: '/media/mkoch/9ee63bf8-5a14-4872-86f2-7f16b120269b/hens_data/hens_checkpoints/d2m_sfno_linear_74chq_sc2_layers8_edim620_wstgl2-epoch70_seed16.nc'
    noise_amplification: .35
    perturbed_var: 'z500'
    integration_steps: 3

data_source:
    _target_: earth2studio.data.GFS  # data source class

cyclone_tracking:
    out_dir: './outputs'

file_output:
    path: './outputs'       # directory to which outfiles are written
    output_vars: ["t2m", 'u10m', 't850', 'q850', 'z500'] # , 'tp06']
    thread_io: False      # write out in seperate thread (needs further testing)
    format:               # io backend class
        _target_: earth2studio.io.NetCDF4Backend
        _partial_: True
        backend_kwargs:
            mode: 'w'
            diskless: False
            persist: False
            chunks:
                ensemble: 1
                time: 1
                lead_time: 1
    cropboxes:
        gulf_of_mexico:
            lat_min: 10
            lat_max: 40
            lon_min: 250
            lon_max: 310
