project: 'helene'
mode: 'cyclone_tracking' # 'base' 'cyclone_tracking' 'diagnostic'
# random_seed: 377777

start_times: ["2024-09-23"]
#ic_block_start: "2024-09-22"
#ic_block_end: "2024-09-29"
#ic_block_step: 12

nsteps: 2 # 40          # number of forecasting steps
nensemble: 2 # 32       # ensemble size per checkpoint
batch_size: 2      # inference batch size

forecast_model:
    architecture: earth2studio.models.px.SFNO   # forecast model class
    package: '/media/mkoch/9ee63bf8-5a14-4872-86f2-7f16b120269b/hens_data/hens_checkpoints'
    max_num_checkpoints: 1                     # max number of checkpoints which will be used

# diagnostic_model:
#     architecture: precip_wrapper.PrecipitationAFNOv2   # diagnostic model class
#     package: '/hens/precip_package'                    # path to diagnostic model package

# diagnostic_models:
#     precip:
#         architecture: precip_wrapper.PAFNO   # diagnostic model class
#         package: 'default'                    # path to diagnostic model package

perturbation:
    method: 'hcbv'             # perturbation method
    perturbed_var: 'z500'      # variable perurbed in seed perturbation
    noise_amplification: .35   # amplification of noise
    skill_path: '/media/mkoch/9ee63bf8-5a14-4872-86f2-7f16b120269b/hens_data/hens_checkpoints/d2m_sfno_linear_74chq_sc2_layers8_edim620_wstgl2-epoch70_seed16.nc'
    integration_steps: 3

data_source:
    # _target_: earth2studio.data.GFS  # data source class
    _target_: earth2studio.data.DataArrayDirectory  # data source class
    dir_path: '/media/mkoch/9ee63bf8-5a14-4872-86f2-7f16b120269b/hens_data/gfs'            # if from disk, path to files

cyclone_tracking:
    out_dir: './outputs'

file_output:
    path: './outputs'       # directory to which outfiles are written
    output_vars: ["t2m", 'u10m', 't850', 'q850', 'z500'] # , 'tp06']
    thread_io: False      # write out in seperate thread (needs further testing)
    format:               # io backend class
        _target_: earth2studio.io.KVBackend
        # _target_: earth2studio.io.XarrayBackend
