project: 'bernd'

ic_block_start: "2021-07-10" # first IC
ic_block_end: "2021-07-11 12:00:00"   # upper boundary for ICs
ic_block_step: 12            # number of hours between individual ICs
nsteps: 2         # number of forecasting steps
nensemble: 4       # ensemble size per checkpoint
batch_size: 2      # inference batch size

forecast_model:
    architecture: earth2studio.models.px.SFNO   # forecast model class
    package: '/media/mkoch/9ee63bf8-5a14-4872-86f2-7f16b120269b/hens_data/hens_checkpoints'
    max_num_checkpoints: 2 # max number of checkpoints which will be used

diagnostic_models:
    rel_hum:
        _target_: earth2studio.models.dx.DerivedRH
        levels: [850,500]
    precipitation:
        architecture: earth2studio.models.dx.PrecipitationAFNO

perturbation:
    _target_: hens_perturbation.HENSPerturbation
    _partial_: True
    skill_path: '/media/mkoch/9ee63bf8-5a14-4872-86f2-7f16b120269b/hens_data/hens_checkpoints/d2m_sfno_linear_74chq_sc2_layers8_edim620_wstgl2-epoch70_seed16.nc' # CAUTION: remove personal paths!!!
    noise_amplification: .35
    perturbed_var: 'z500'
    integration_steps: 3

data_source:
    _target_: earth2studio.data.ARCO  # data source class

file_output:
    path: './outputs'       # directory to which outfiles are written
    output_vars: ["t2m", 'u10m', 'r500', 'tp06']
    thread_io: False      # write out in seperate thread (needs further testing)
    format:               # io backend class
        _target_: earth2studio.io.ZarrBackend
        _partial_: True
        chunks:
            ensemble: 1
            time: 1
            lead_time: 1
        backend_kwargs:
            overwrite: True
