# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import json
from collections.abc import Generator, Iterator

import numpy as np
import torch
import torch.nn as nn
from loguru import logger

from earth2studio.models.auto import AutoModelMixin, Package
from earth2studio.models.batch import batch_coords, batch_func
from earth2studio.models.px.atlas import VARIABLES, npdt64_to_naive_utc
from earth2studio.models.px.base import PrognosticModel
from earth2studio.models.px.utils import PrognosticMixin
from earth2studio.utils import handshake_coords, handshake_dim
from earth2studio.utils.imports import (
    OptionalDependencyFailure,
    check_optional_dependencies,
)
from earth2studio.utils.type import CoordSystem

try:
    from physicsnemo import Module
except ImportError:
    OptionalDependencyFailure("atlas")
    Module = None


@check_optional_dependencies()
class AtlasCRPS(torch.nn.Module, AutoModelMixin, PrognosticMixin):
    """Atlas CRPS ensemble prognostic model for ERA5 variables on a 0.25 degree global
    lat-lon grid.

    AtlasCRPS consumes two input lead times (t-6h and t) and predicts a single step at
    t+6h on a 721x1440 latitude-longitude grid. The model predicts a low-resolution
    residual which is decoded to full resolution by an autoencoder. Ensemble members are
    generated by calling the model repeatedly from the same initial condition, each
    forward pass draws a new noise vector that modulates every transformer block.

    Parameters
    ----------
    model : nn.Module
        CRPS latent transformer predicting a normalized low-resolution residual.
    model_processor : nn.Module
        Processor providing the state and residual normalizers, the static invariant
        channels, the cosine zenith angle channel, the low-resolution downsampling and
        the low-resolution conditioning.
    autoencoder : nn.Module
        Autoencoder decoding the low-resolution residual to full resolution.
    autoencoder_processor : nn.Module
        Autoencoder processor mapping the decoded residual back to physical units.

    Warning
    -------
    This model is expected to use the iterator interface for autoregressive
    rollouts longer than one step. Iteratively using the ``__call__`` and
    ``prep_next_input`` methods will not produce correct results, since the model
    performs autoregressive timestepping using a full-resolution physical state
    and an internal low-resolution latent state.

    Note
    ----
    Ensemble noise is drawn from the global PyTorch generator, use
    :func:`torch.manual_seed` for reproducible members.

    Note
    ----
    For best inference performance, set the environment variable `TORCH_ALLOW_TF32_CUBLAS_OVERRIDE=1`.
    This is on by default in NGC containers, but other environments may need to set it manually.

    Badges
    ------
    region:global class:medium-range product:wind product:precip product:temp product:atmos year:2026
    gpu:80gb
    provider:nvidia backend:pytorch
    """

    DT = np.timedelta64(6, "h")

    def __init__(
        self,
        model: nn.Module,
        model_processor: nn.Module,
        autoencoder: nn.Module,
        autoencoder_processor: nn.Module,
    ) -> None:
        super().__init__()
        self.model = model
        self.model_processor = model_processor
        self.autoencoder = autoencoder
        self.autoencoder_processor = autoencoder_processor

    def input_coords(self) -> CoordSystem:
        """Input coordinate system expected by AtlasCRPS.

        Notes
        -----
        - Lead times are fixed to [-6h, 0h].
        - Variables are defined by the `VARIABLES` of the Atlas model.
        - Spatial grid is 0.25 degree lat-lon: 721 latitudes, 1440 longitudes.

        Returns
        -------
        CoordSystem
            Ordered dictionary with keys:
            - 'lead_time' : np.ndarray[np.timedelta64] of shape (2,)
            - 'variable' : np.ndarray[str] of shape (n_variables,)
            - 'lat' : np.ndarray[float] of shape (721,)
            - 'lon' : np.ndarray[float] of shape (1440,)
        """
        coords = CoordSystem(
            {
                "batch": np.empty(0),
                "time": np.empty(0),
                "lead_time": np.array([-self.DT, np.timedelta64(0, "h")]),
                "variable": np.array(VARIABLES),
                "lat": np.linspace(90.0, -90.0, 721, dtype=np.float32),
                "lon": np.linspace(
                    0.0,
                    360.0,
                    1440,
                    dtype=np.float32,
                    endpoint=False,
                ),
            }
        )
        return coords

    @batch_coords()
    def output_coords(self, input_coords: CoordSystem) -> CoordSystem:
        """Output coordinate system produced by a single AtlasCRPS step (t+6h).

        Parameters
        ----------
        input_coords : CoordSystem
            Coordinate system associated with the input to the forward pass.

        Returns
        -------
        CoordSystem
            Ordered dictionary with keys:
            - 'time' : np.ndarray[np.datetime64] (copied from input if present)
            - 'lead_time' : np.timedelta64 set to +6h
            - 'variable' : np.ndarray[str] matching `VARIABLES`
            - 'lat' : np.ndarray[float] (copied from input if present, else 721 values)
            - 'lon' : np.ndarray[float] (copied from input if present, else 1440 values)
        """
        output_coords = CoordSystem(
            {
                "batch": np.empty(0),
                "time": np.empty(0),
                "lead_time": np.array([self.DT]),
                "variable": np.array(VARIABLES),
                "lat": np.linspace(90.0, -90.0, 721, dtype=np.float32),
                "lon": np.linspace(
                    0.0,
                    360.0,
                    1440,
                    dtype=np.float32,
                    endpoint=False,
                ),
            }
        )

        test_coords = input_coords.copy()
        test_coords["lead_time"] = (
            test_coords["lead_time"] - input_coords["lead_time"][-1]
        )
        target_input_coords = self.input_coords()
        for i, key in enumerate(target_input_coords):
            if key not in ["batch", "time"]:
                handshake_dim(test_coords, key, i)
                handshake_coords(test_coords, target_input_coords, key)

        output_coords["batch"] = input_coords["batch"]
        output_coords["time"] = input_coords["time"]

        output_coords["lead_time"] = (
            input_coords["lead_time"][-1] + output_coords["lead_time"]
        )

        return output_coords

    @batch_func()
    def prep_next_input(
        self,
        x_pred: torch.Tensor,
        coords_pred: CoordSystem,
        x: torch.Tensor,
        coords: CoordSystem,
    ) -> tuple[torch.Tensor, CoordSystem]:
        """Prepare the next input for the AtlasCRPS model. Since the input requires two
        lead times but the model predicts one, we update a sliding window to make
        autoregressive predictions.

        Parameters
        ----------
        x_pred : torch.Tensor
            Predicted tensor from the previous step.
        coords_pred : CoordSystem
            Coordinates describing `x_pred`.
        x : torch.Tensor
            Input tensor from the previous step.
        coords : CoordSystem
            Coordinates describing `x`.
        """
        x_next = x.clone()
        # Fill latest step with most recent prediction
        x_next[:, :, 1:, :, :, :] = x_pred[:, :, :1, :, :, :]
        # Shift the previous latest step to the earlier position
        x_next[:, :, :1, :, :, :] = x[:, :, 1:, :, :, :]
        coords_next = coords.copy()
        coords_next["lead_time"] = coords_next["lead_time"] + self.DT
        return x_next, coords_next

    @torch.inference_mode()
    def _forward(
        self,
        x: torch.Tensor,
        coords: CoordSystem,
        prev_latents: tuple[torch.Tensor, torch.Tensor] | None = None,
    ) -> tuple[torch.Tensor, tuple[torch.Tensor, torch.Tensor]]:
        """Forward pass of the prognostic model, integrating a single 6h step.

        Parameters
        ----------
        x : torch.Tensor
            Input tensor of shape (lead_time, variable, lat, lon) corresponding to the
            coordinate system. Lead times expected: [-6h, 0h].
        coords : CoordSystem
            Coordinate dictionary describing `x`.
        prev_latents : tuple[torch.Tensor, torch.Tensor], optional
            Low-resolution history and current latents from the previous forecast step.
            If provided, they will be reused instead of downsampling the input
            high-resolution state, by default None

        Returns
        -------
        tuple[torch.Tensor, tuple[torch.Tensor, torch.Tensor]]
            Tuple containing the decoded forecast at t+6h and the history and current
            latents to use for the following step.
        """

        if x.ndim != 4:
            raise ValueError(
                f"Internal forward pass expects x of shape (lead_time, variable, lat, lon), got {x.shape}"
            )
        if len(coords["lead_time"]) != 2:
            raise ValueError(
                f"Internal forward pass expects coords['lead_time'] of length 2, got {len(coords['lead_time'])}"
            )

        # Prepare input tensor and date metadata
        x_cur, x_prev = x[-1:, :, :, :], x[:1, :, :, :]
        t = coords["time"][0] + coords["lead_time"][-1]
        current_date = np.array([[npdt64_to_naive_utc(t)]])
        low_res_shape = self.model_processor.downsample_grid_shape

        # Preprocess to build high-res state (physical state, zenith and static
        # channels) and the low-res normalized state
        high_res, low_res = self.model_processor.preprocess_input(x_cur, current_date)
        if prev_latents is None:
            prev = self.model_processor.normalizer_in.normalize(x_prev)
            prev = self.model_processor.intep(prev, low_res_shape)
        else:
            prev = prev_latents[0].clone()
            low_res = prev_latents[1].clone()

        conditioning = self.model_processor.preprocess_conditioning(high_res, low_res)
        residual_latent = self.model(prev, conditioning)

        # Decode the latent residual and return to state space
        pred = self.autoencoder(high_res, residual_latent)
        pred = self.autoencoder_processor.postprocess(pred, x_cur)

        # Update latent residual prediction into latent state prediction
        state_latent = self.model_processor.normalizer_out.unnormalize(residual_latent)
        state_latent = state_latent + self.model_processor.normalizer_in.unnormalize(
            low_res
        )
        state_latent = self.model_processor.normalizer_in.normalize(state_latent)

        return pred, (low_res, state_latent)

    @torch.inference_mode()
    @batch_func()
    def __call__(
        self, x: torch.Tensor, coords: CoordSystem
    ) -> tuple[torch.Tensor, CoordSystem]:
        """Forward pass of the prognostic model, integrating a single 6h step.

        Parameters
        ----------
        x : torch.Tensor
            Input tensor of shape (..., lead_time, variable, lat, lon) corresponding
            to the coordinate system. Lead times expected: [-6h, 0h].
        coords : CoordSystem
            Coordinate dictionary describing `x`.

        Returns
        -------
        tuple[torch.Tensor, CoordSystem]
            Output tensor advanced to t+6h and its coordinate system.
        """

        # Sanitize NaNs in input sst
        if torch.isnan(x).any():
            logger.info("AtlasCRPS input contains NaNs, replacing with 0.0")
            x = torch.nan_to_num(x, nan=0.0)

        output_coords = self.output_coords(coords)
        out = torch.empty_like(x[:, :, :1])

        # Loop over init times
        for i, _ in enumerate(coords["batch"]):
            for j, _ in enumerate(coords["time"]):
                slice_coords = coords.copy()
                slice_coords["time"] = slice_coords["time"][j : j + 1]
                pred, _ = self._forward(x[i, j, :], slice_coords)
                out[i, j, :] = pred

        return out, output_coords

    @torch.inference_mode()
    def _call_with_latents(
        self,
        x: torch.Tensor,
        coords: CoordSystem,
        prev_latents: (
            list[list[tuple[torch.Tensor, torch.Tensor] | None]] | None
        ) = None,
    ) -> tuple[
        torch.Tensor,
        CoordSystem,
        list[list[tuple[torch.Tensor, torch.Tensor] | None]],
    ]:
        """Internal helper that handles cached latents during autoregressive rollout."""

        # Sanitize NaNs in input sst
        if torch.isnan(x).any():
            logger.info("AtlasCRPS input contains NaNs, replacing with 0.0")
            x = torch.nan_to_num(x, nan=0.0)

        output_coords = self.output_coords(coords)
        out = torch.empty_like(x[:, :, :1])
        latents_out: list[list[tuple[torch.Tensor, torch.Tensor] | None]] = [
            [None for _ in coords["time"]] for _ in coords["batch"]
        ]

        for i, _ in enumerate(coords["batch"]):
            for j, _ in enumerate(coords["time"]):
                slice_coords = coords.copy()
                slice_coords["time"] = slice_coords["time"][j : j + 1]
                latents = None
                if prev_latents is not None:
                    latents = prev_latents[i][j]
                pred, pred_latents = self._forward(x[i, j, :], slice_coords, latents)
                out[i, j, :] = pred
                latents_out[i][j] = pred_latents

        return out, output_coords, latents_out

    def create_iterator(
        self, x: torch.Tensor, coords: CoordSystem
    ) -> Iterator[tuple[torch.Tensor, CoordSystem]]:
        """Create an iterator that yields the initial state then successive 6h steps.

        Parameters
        ----------
        x : torch.Tensor
            Initial data tensor on device representing the initial condition.
        coords : CoordSystem
            Coordinate system for the initial data tensor.

        Yields
        ------
        Iterator[tuple[torch.Tensor, CoordSystem]]
            Iterator yielding successive model outputs and their coordinates.
        """
        yield from self._default_generator(x, coords)

    @batch_func()
    def _default_generator(
        self, x: torch.Tensor, coords: CoordSystem
    ) -> Generator[tuple[torch.Tensor, CoordSystem], None, None]:
        coords = coords.copy()

        # Validate coords
        _ = self.output_coords(coords)

        # Sanitize NaNs in input sst
        if torch.isnan(x).any():
            logger.info("AtlasCRPS input contains NaNs, replacing with 0.0")
            x = torch.nan_to_num(x, nan=0.0)

        # Yield initial condition
        ic_coords = coords.copy()
        ic_coords["lead_time"] = ic_coords["lead_time"][-1:]
        yield x[:, :, -1:, :, :, :], ic_coords

        latent_cache: list[list[tuple[torch.Tensor, torch.Tensor] | None]] | None = None
        while True:
            # Front hook
            x, coords = self.front_hook(x, coords)
            # Forward
            x_pred, coords_pred, latent_cache = self._call_with_latents(
                x, coords, prev_latents=latent_cache
            )
            # Rear hook
            x_pred, coords_pred = self.rear_hook(x_pred, coords_pred)
            yield x_pred, coords_pred.copy()

            # Prepare next input
            x, coords = self.prep_next_input(x_pred, coords_pred, x, coords)

    @classmethod
    def load_default_package(cls) -> Package:
        """Load the default package for the AtlasCRPS model.

        Note
        ----
        This package is the same merged Atlas-SI / Atlas-CRPS HuggingFace package used
        by :func:`earth2studio.models.px.Atlas.load_default_package`, laid out with a
        `crps/config.json` manifest and the CRPS model and processor checkpoints under
        `crps/genmodel`, sharing the `autoencoders/` directory with the Atlas (SI)
        `si/` subtree.
        """
        package = Package(
            "hf://nvidia/atlas-era5@893a38550aa313c97c41382a5003d209d60a840b",
            cache_options={
                "cache_storage": Package.default_cache("atlas"),
                "same_names": False,  # prevents overwrites from files with same name in different directories
            },
        )
        return package

    @classmethod
    @check_optional_dependencies()
    def load_model(cls, package: Package) -> PrognosticModel:
        """Instantiate and load AtlasCRPS from a package.

        The autoencoder used to decode the low-resolution residual is shared with the
        Atlas model but described directly in the CRPS config's `package.autoencoders`
        entry, so it is loaded from the same package rather than a separate one.
        """
        # Resolve the package-root config.json so HuggingFace records the download
        # (its content is not used here); tolerate its absence.
        try:
            package.resolve("config.json")
        except FileNotFoundError:
            pass

        with open(package.resolve("crps/config.json")) as f:
            config = json.load(f)
        genmodel_config = config["package"]["genmodel"]

        model = Module.from_checkpoint(package.resolve(genmodel_config["model_path"]))
        model.eval()

        model_processor = Module.from_checkpoint(
            package.resolve(genmodel_config["processor_path"])
        )
        model_processor.eval()

        autoencoder_config = config["package"]["autoencoders"][0]
        autoencoder = Module.from_checkpoint(
            package.resolve(autoencoder_config["model_path"])
        )
        autoencoder.eval()

        autoencoder_processor = Module.from_checkpoint(
            package.resolve(autoencoder_config["processor_path"])
        )
        autoencoder_processor.eval()

        return cls(
            model=model,
            model_processor=model_processor,
            autoencoder=autoencoder,
            autoencoder_processor=autoencoder_processor,
        )
